import { ReviewResponse, ReviewFinding } from "@/lib/gemini";

/**
 * Formats a structured AI review into a professional GitHub Markdown comment
 */
export function formatGitHubComment(review: ReviewResponse, modelName: string): string {
  let comment = `# 🛡️ MergeGuard AI Review\n\n`;

  comment += `## 📝 Summary\n${review.summary}\n\n`;

  const categories: { label: string; key: keyof ReviewResponse }[] = [
    { label: "🐞 Bugs", key: "bugs" },
    { label: "🔐 Security", key: "security" },
    { label: "⚡ Performance", key: "performance" },
    { label: "🌬️ Code Smells", key: "codeSmells" },
    { label: "🏛️ Architecture", key: "architectureConcerns" },
    { label: "💡 Suggestions", key: "suggestions" },
  ];

  for (const cat of categories) {
    const findings = review[cat.key] as ReviewFinding[];
    if (findings && findings.length > 0) {
      comment += `## ${cat.label}\n`;
      findings.forEach((finding) => {
        comment += `### ${getSeverityEmoji(finding.severity)} ${finding.title}\n`;
        comment += `**File:** \`${finding.file}:${finding.line}\` | **Severity:** \`${finding.severity.toUpperCase()}\`\n\n`;
        comment += `${finding.description}\n\n`;
        comment += `> **💡 Recommendation:** ${finding.recommendation}\n\n`;
        if (finding.codeSnippet) {
          comment += `\`\`\`${getFileExtension(finding.file)}\n${finding.codeSnippet}\n\`\`\`\n\n`;
        }
        comment += `---\n\n`;
      });
    }
  }

  comment += `\n---\n`;
  comment += `*Generated by **MergeGuard AI** using \`${modelName}\` • ${new Date().toUTCString()}*`;

  return comment;
}

function getSeverityEmoji(severity: string): string {
  switch (severity.toLowerCase()) {
    case "critical": return "🔴";
    case "high": return "🟠";
    case "medium": return "🟡";
    case "low": return "🔵";
    default: return "⚪";
  }
}

function getFileExtension(filename: string): string {
  const parts = filename.split('.');
  return parts.length > 1 ? parts.pop() || "" : "";
}
