import { ReviewResponse, ReviewFinding, AnalysisMetadata } from "@/lib/gemini";

/**
 * Formats a structured AI review into a professional, enterprise-grade GitHub Markdown comment
 */
export function formatGitHubComment(review: ReviewResponse, metadata: AnalysisMetadata): string {
  let comment = `# 🛡️ MergeGuard Core Audit Report\n\n`;

  // 1. Overall Risk Assessment
  const riskScore = calculateRiskScore(review);
  const riskLevel = getRiskLevel(riskScore);
  const progressBar = getProgressBar(riskScore);

  comment += `## 🛡️ Overall Risk Assessment\n\n`;
  comment += `${getRiskEmoji(riskLevel)} **${riskLevel.toUpperCase()}**\n`;
  comment += `**Risk Score: ${riskScore}/100**\n\n`;
  comment += `${progressBar}  ${riskScore}/100\n\n`;

  const riskContributors = getRiskContributors(review);
  if (riskContributors.length > 0) {
    comment += `**Risk contributors:**\n\n`;
    riskContributors.forEach(c => comment += `* ${c}\n`);
    comment += `\n`;
  }

  comment += `## 📝 Executive Summary\n${review.summary}\n\n`;

  comment += `---\n\n`;

  const categories: { label: string; key: keyof ReviewResponse }[] = [
    { label: "🐞 Bugs", key: "bugs" },
    { label: "🔐 Security", key: "security" },
    { label: "⚡ Performance", key: "performance" },
    { label: "🌬️ Code Smells", key: "codeSmells" },
    { label: "🏛️ Architecture", key: "architectureConcerns" },
    { label: "💡 Suggestions", key: "suggestions" },
  ];

  for (const cat of categories) {
    const findings = review[cat.key] as ReviewFinding[];
    if (findings && findings.length > 0) {
      comment += `## ${cat.label}\n\n`;
      findings.forEach((finding) => {
        const cweInfo = finding.cwe ? ` · \`${finding.cwe}\`` : "";
        comment += `### ${getSeverityEmoji(finding.severity)} ${finding.title}${cweInfo}\n`;
        comment += `**File:** \`${finding.file}:${finding.line}\` | **Severity:** \`${finding.severity.toUpperCase()}\` | **Confidence:** \`${finding.confidence.toUpperCase()}\`\n\n`;
        
        comment += `${finding.description}\n\n`;
        
        comment += `⚠️ **Impact:** ${finding.impact}\n\n`;
        
        comment += `> **💡 Recommendation:** ${finding.recommendation}\n\n`;
        
        if (finding.codeSnippet) {
          comment += `\`\`\`${getFileExtension(finding.file)}\n${finding.codeSnippet}\n\`\`\`\n\n`;
        }
        comment += `---\n\n`;
      });
    }
  }

  // 3. Positive Findings
  if (review.positiveFindings && review.positiveFindings.length > 0) {
    comment += `## ✨ Positive Findings\n\n`;
    review.positiveFindings.slice(0, 3).forEach(pf => {
      comment += `* ${pf}\n`;
    });
    comment += `\n---\n\n`;
  }

  // 4. Analysis Summary
  const totalFindings = (review.bugs.length + review.security.length + review.performance.length + review.codeSmells.length + review.architectureConcerns.length + review.suggestions.length);
  
  comment += `## 📊 Analysis Summary\n\n`;
  comment += `| Metric | Value |\n`;
  comment += `| :--- | :--- |\n`;
  comment += `| **Model** | \`${metadata.model}\` |\n`;
  comment += `| **Cache** | \`${metadata.cacheStatus.toUpperCase()}\` |\n`;
  comment += `| **Chunks** | \`${metadata.chunkCount}\` |\n`;
  comment += `| **Tokens** | \`~${(metadata.totalTokens / 1000).toFixed(1)}k\` |\n`;
  comment += `| **Duration** | \`${(metadata.duration / 1000).toFixed(1)}s\` |\n`;
  comment += `| **Findings** | \`${totalFindings} issues detected\` |\n\n`;

  comment += `\n*Generated by **MergeGuard Core** • ${new Date().toUTCString()}*`;

  return comment;
}

function calculateRiskScore(review: ReviewResponse): number {
  let score = 0;
  const allFindings = [
    ...review.bugs,
    ...review.security,
    ...review.performance,
    ...review.codeSmells,
    ...review.architectureConcerns,
    ...review.suggestions
  ];

  allFindings.forEach(f => {
    switch (f.severity.toLowerCase()) {
      case "critical": score += 25; break;
      case "high": score += 15; break;
      case "medium": score += 8; break;
      case "low": score += 3; break;
    }
  });

  return Math.min(score, 100);
}

function getRiskLevel(score: number): "critical" | "high" | "medium" | "low" {
  if (score >= 80) return "critical";
  if (score >= 50) return "high";
  if (score >= 20) return "medium";
  return "low";
}

function getRiskEmoji(level: string): string {
  switch (level) {
    case "critical": return "🛑";
    case "high": return "🔴";
    case "medium": return "🟡";
    case "low": return "🟢";
    default: return "⚪";
  }
}

function getProgressBar(score: number): string {
  const totalBlocks = 20;
  const filledBlocks = Math.round((score / 100) * totalBlocks);
  const emptyBlocks = totalBlocks - filledBlocks;
  return "█".repeat(filledBlocks) + "░".repeat(emptyBlocks);
}

function getRiskContributors(review: ReviewResponse): string[] {
  const contributors: string[] = [];
  const allFindings = [
    ...review.bugs,
    ...review.security,
    ...review.performance,
    ...review.codeSmells,
    ...review.architectureConcerns
  ];

  const criticalCount = allFindings.filter(f => f.severity === 'critical').length;
  const highCount = allFindings.filter(f => f.severity === 'high').length;
  const mediumCount = allFindings.filter(f => f.severity === 'medium').length;

  if (criticalCount > 0) contributors.push(`${criticalCount} Critical finding${criticalCount > 1 ? 's' : ''}`);
  if (highCount > 0) contributors.push(`${highCount} High finding${highCount > 1 ? 's' : ''}`);
  if (mediumCount > 0) contributors.push(`${mediumCount} Medium finding${mediumCount > 1 ? 's' : ''}`);

  // Specific themes if found multiple times (mock logic for now based on titles)
  if (review.security.some(s => s.title.toLowerCase().includes('validation') || s.description.toLowerCase().includes('validation'))) {
    contributors.push("Missing request validation");
  }
  if (review.security.some(s => s.title.toLowerCase().includes('xss') || s.description.toLowerCase().includes('sanitize'))) {
    contributors.push("Unsafe user input rendering");
  }

  return contributors.slice(0, 5);
}

function getSeverityEmoji(severity: string): string {
  switch (severity.toLowerCase()) {
    case "critical": return "🛑";
    case "high": return "🔴";
    case "medium": return "🟡";
    case "low": return "🔵";
    default: return "⚪";
  }
}

function getFileExtension(filename: string): string {
  const parts = filename.split('.');
  return parts.length > 1 ? parts.pop() || "" : "";
}
